const sportsNames = [
  "Airsoft",
  "American Football",
  "Aquathlon",
  "Archery",
  "Athletics (Track and Field)",
  "Badminton",
  "Barefoot Skiing",
  "Baseball",
  "Basketball",
  "Basque Pelota",
  "Biathlon",
  "Billiards",
  "BMX",
  "Bobsleigh",
  "Bodybuilding",
  "Bossaball",
  "Bowling",
  "Boxing",
  "Canoeing",
  "Caving (Spelunking)",
  "Cheerleading",
  "Chess Boxing",
  "Cornhole",
  "Cricket",
  "Curling",
  "Cycling",
  "Dance Sport",
  "Darts",
  "Dodgeball",
  "Dog Sledding",
  "Dragon Boat",
  "Dragon Boat Racing",
  "Equestrian",
  "Esports",
  "Fencing",
  "Field Archery",
  "Field Hockey",
  "Figure Skating",
  "Floorball",
  "Footgolf",
  "Freediving",
  "Freestyle Skiing",
  "Frisbee (Ultimate)",
  "Frisbee Golf (Disc Golf)",
  "Gaelic Football",
  "Golf",
  "Gymnastics",
  "Handball",
  "Hang Gliding",
  "Highland Games",
  "Hockey",
  "Hurling",
  "Hydrofoil Surfing",
  "Ice Hockey",
  "Inline Hockey",
  "Inline Skating",
  "Judo",
  "Jet Ski Racing",
  "Kabaddi",
  "Karate",
  "Kayaking",
  "Kickboxing",
  "Kitesurfing",
  "Kiteboarding",
  "Lacrosse",
  "Luge",
  "Modern Pentathlon",
  "Motorsport (e.g., Formula 1, MotoGP)",
  "Mountain Biking",
  "Muay Thai",
  "MMA (Mixed Martial Arts)",
  "Netball",
  "Nordic Combined",
  "Orienteering",
  "Paddleboarding",
  "Paintball",
  "Pankration",
  "Paragliding",
  "Parkour",
  "Petanque",
  "Pickleball",
  "Polo",
  "Powerlifting",
  "Quidditch",
  "Racquetball",
  "Rhythmic Gymnastics",
  "Rock Climbing",
  "Rodeo",
  "Roller Derby",
  "Rowing",
  "Rugby",
  "Sailing",
  "Sandboarding",
  "Savate",
  "Sepak Takraw",
  "Shooting",
  "Skeleton",
  "Skiing",
  "Skateboarding",
  "Snooker",
  "Snowboarding",
  "Snowshoeing",
  "Soccer",
  "Softball",
  "Speed Skating",
  "Spikeball",
  "Squash",
  "Sumo Wrestling",
  "Surfing",
  "Swimming",
  "Synchronized Swimming",
  "Table Tennis",
  "Taekwondo",
  "Tennis",
  "Triathlon",
  "Tug of War",
  "Underwater Hockey",
  "Underwater Rugby",
  "Volleyball",
  "Water Polo",
  "Weightlifting",
  "Windsurfing",
  "Wrestling",
];
export default sportsNames;
